// Pre-encode page numbers 1..MAX through the conlang codec and emit a
// `@counter-style` CSS file.
//
// WeasyPrint only knows real page numbers during
// pagination, so the glyphs cannot be computed per page at render time.
// Instead we embed them as a fixed counter style whose Nth symbol is the glyph string
// for page N; the @page margin box then resolves them with
// `counter(page, conlang-page-numbers)`.

import { parseArgs } from "node:util"

import { encode } from "../tools/conlang/src/conlang.js"

const { values } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    max: {
      type: "string"
    },
    output: {
      type: "string"
    },
    help: {
      type: "boolean",
      short: "h"
    },
  },
  allowPositionals: false,
})

if (values.help) {
  console.log(
    "Usage: bun scripts/gen_conlang_pagenums.js --max <N> --output <file.css>\n" +
      "\n" +
      "Emits an @counter-style mapping page numbers 1..N to conlang glyphs.\n"
  )
  process.exit(0)
}

const max = Number.parseInt(values.max ?? "", 10)

if (!Number.isInteger(max) || max < 1) {
  console.error("Error: --max <N> must be a positive integer")
  process.exit(1)
}
if (!values.output) {
  console.error("Error: --output <file.css> is required")
  process.exit(1)
}

// One batched encode call: a single line `1|2|...|N`. `|` passes through
// unencoded, so each number is encoded independently (a number sign per run).
const line = Array
  .from(
    { length: max },
    (_, i) => i + 1
  ).join("|")
const glyphs = encode(line).split("|")

if (glyphs.length !== max) {
  console.error(
    `Error: expected ${max} encoded entries, got ${glyphs.length}. ` +
    "The '|' separator is not altered by the encoder."
  )
  process.exit(1)
}

// `system: fixed 1`:
//    symbol[0] is page 1, symbol[1] is page 2, ...
//
// Beyond the list the counter style falls back to its defaults
const symbols = glyphs.map((g) => `"${g}"`).join(" ")
const css =
  "/* Generated by scripts/gen_conlang_pagenums.js -- do not edit by hand. */\n" +
  "@counter-style conlang-page-numbers {\n" +
  "  system: fixed 1;\n" +
  `  symbols: ${symbols};\n` +
  '  suffix: "";\n' +
  "}\n"

await Bun.write(values.output, css)
console.log(`wrote ${glyphs.length} page-number glyphs to ${values.output}`)
